name: AIRT - Relatório Automático de Testes

on:
  workflow_run:
    workflows: ["DEPLOY_GITHUB_PAGES"]
    types:
      - completed

  workflow_dispatch: # Permite execução manual

  schedule:
    - cron: '0 8 * * *' # Executar diariamente às 8h da manhã

jobs:
  airt_report:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    env:
      # CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }}
      # CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
      # CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
      # SPACE_KEY: ${{ secrets.CONFLUENCE_SPACE_KEY }}
      # PARENT_PAGE_ID: ${{ secrets.CONFLUENCE_PARENT_PAGE_ID }}

      CONFLUENCE_URL: https://correadev.atlassian.net/
      CONFLUENCE_USERNAME: correa.dev@gmail.com
      CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
      SPACE_KEY: MFS
      PARENT_PAGE_ID: 1234567890

    steps:
      - name: ⬇️ Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 📦 Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/scripts/requirements.txt
        working-directory: ${{ github.workspace }}

      - name: 🔍 Verificar estrutura de arquivos
        run: |
          echo "Verificando estrutura de scripts..."
          ls -la .github/scripts/
          echo "Verificando se os scripts principais existem..."
          test -f .github/scripts/main.py
          test -f .github/scripts/extract_robot_data.py
          test -f .github/scripts/extract_postman_data.py
          test -f .github/scripts/analyze_results.py
          test -f .github/scripts/publish_to_confluence.py
          echo "✅ Estrutura de arquivos OK"

      - name: 📝 Executar AIRT - Relatório Automático
        run: |
          python .github/scripts/main.py --verbose
        working-directory: ${{ github.workspace }}
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: 📊 Verificar arquivos gerados
        if: always()
        run: |
          echo "Verificando arquivos de saída..."
          ls -la output/ || echo "Diretório output não encontrado"
          echo "Conteúdo do diretório de trabalho:"
          ls -la

      - name: 📤 Upload dos arquivos de saída
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: airt-output-files
          path: |
            output/
            resultados/
          retention-days: 7

      - name: 🚨 Notificar falha
        if: failure()
        run: |
          echo "❌ AIRT falhou durante a execução"
          echo "Verifique os logs acima para mais detalhes"
          exit 1
